### ISSUE TITLE
Avoid creating multiple versions of the same file uploaded multiple times

### ISSUE THREAD

**Issue by sks444** [mbraak/django-file-form#323]
In case of multiple file upload, if you upload the same file multiple times you get multiple versions of it. It does not get replaced with the new version as one might expect.

**Comment by mbraak** [comment]
The same file: is that a file with the same filename? Or a file with exactly the same contents?

**Comment by sks444** [comment]
A file with same filename.

File with same contents but with different filename should be considered as a different file I guess.

**Comment by sks444** [comment]
>File with same contents but with different filename should be considered as a different file I guess.

At least on the client side. One might want to do server side validation to validate the contents and raise error. But I think files with same filename could be validated at client side.

**Comment by mbraak** [comment]
I'll add this to the todo-list.

**Comment by sks444** [comment]
Thanks.

**Comment by BoPeng** [comment]
I reported this problem before https://github.com/mbraak/django-file-form/issues/274 . To me files with the same filename should overwrite files with the same name, regardless of content, because it is much more likely that a user wants to upload a newer version.

I think a proper solution is that for all files added/dropped, we check the filename and remove existing files, regardless it is is completed (remove existing uploaded files) or failed (resume upload). The latter will partially address #293.

**Comment by BoPeng** [comment]
https://github.com/mbraak/django-file-form/pull/333

I proposed a PR, @sks444 please let us know if this is good enough for your application.

**Comment by mbraak** [comment]
Pr #333 is merged

**Comment by BoPeng** [comment]
There is a minor problem that the new files are always appended to the end (while the old ones are removed). It should not be too difficult to change

https://github.com/mbraak/django-file-form/blob/da3dd57a0db4d25d1671dd080960330a72b494b0/frontend/src/upload_file.ts#L198

to fix this.

**Comment by mbraak** [comment]
Ok, I'll make a note of that.

**Comment by mbraak** [comment]
Closing the issue. Note that the 'order issue' mentioned above is still on the todo list.
